// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/mediapipe_face.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class MediapipeFaceBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MediapipeFaceBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MediapipeFaceBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<MpFaceMeshContext> mp_face_mesh_create(
    ffi.Pointer<ffi.Char> model_path,
    ffi.Pointer<MpFaceMeshCreateOptions> options,
  ) {
    return _mp_face_mesh_create(model_path, options);
  }

  late final _mp_face_mesh_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<MpFaceMeshContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<MpFaceMeshCreateOptions>,
          )
        >
      >('mp_face_mesh_create');
  late final _mp_face_mesh_create = _mp_face_mesh_createPtr
      .asFunction<
        ffi.Pointer<MpFaceMeshContext> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<MpFaceMeshCreateOptions>,
        )
      >();

  void mp_face_mesh_destroy(ffi.Pointer<MpFaceMeshContext> context) {
    return _mp_face_mesh_destroy(context);
  }

  late final _mp_face_mesh_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<MpFaceMeshContext>)>
      >('mp_face_mesh_destroy');
  late final _mp_face_mesh_destroy = _mp_face_mesh_destroyPtr
      .asFunction<void Function(ffi.Pointer<MpFaceMeshContext>)>();

  ffi.Pointer<MpFaceMeshResult> mp_face_mesh_process(
    ffi.Pointer<MpFaceMeshContext> context,
    ffi.Pointer<MpImage> image,
    ffi.Pointer<MpNormalizedRect> override_rect,
    int rotation_degrees,
    int mirror_horizontal,
  ) {
    return _mp_face_mesh_process(
      context,
      image,
      override_rect,
      rotation_degrees,
      mirror_horizontal,
    );
  }

  late final _mp_face_mesh_processPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<MpFaceMeshResult> Function(
            ffi.Pointer<MpFaceMeshContext>,
            ffi.Pointer<MpImage>,
            ffi.Pointer<MpNormalizedRect>,
            ffi.Int32,
            ffi.Uint8,
          )
        >
      >('mp_face_mesh_process');
  late final _mp_face_mesh_process = _mp_face_mesh_processPtr
      .asFunction<
        ffi.Pointer<MpFaceMeshResult> Function(
          ffi.Pointer<MpFaceMeshContext>,
          ffi.Pointer<MpImage>,
          ffi.Pointer<MpNormalizedRect>,
          int,
          int,
        )
      >();

  ffi.Pointer<MpFaceMeshResult> mp_face_mesh_process_nv21(
    ffi.Pointer<MpFaceMeshContext> context,
    ffi.Pointer<MpNv21Image> image,
    ffi.Pointer<MpNormalizedRect> override_rect,
    int rotation_degrees,
    int mirror_horizontal,
  ) {
    return _mp_face_mesh_process_nv21(
      context,
      image,
      override_rect,
      rotation_degrees,
      mirror_horizontal,
    );
  }

  late final _mp_face_mesh_process_nv21Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<MpFaceMeshResult> Function(
            ffi.Pointer<MpFaceMeshContext>,
            ffi.Pointer<MpNv21Image>,
            ffi.Pointer<MpNormalizedRect>,
            ffi.Int32,
            ffi.Uint8,
          )
        >
      >('mp_face_mesh_process_nv21');
  late final _mp_face_mesh_process_nv21 = _mp_face_mesh_process_nv21Ptr
      .asFunction<
        ffi.Pointer<MpFaceMeshResult> Function(
          ffi.Pointer<MpFaceMeshContext>,
          ffi.Pointer<MpNv21Image>,
          ffi.Pointer<MpNormalizedRect>,
          int,
          int,
        )
      >();

  void mp_face_mesh_release_result(ffi.Pointer<MpFaceMeshResult> result) {
    return _mp_face_mesh_release_result(result);
  }

  late final _mp_face_mesh_release_resultPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<MpFaceMeshResult>)>
      >('mp_face_mesh_release_result');
  late final _mp_face_mesh_release_result = _mp_face_mesh_release_resultPtr
      .asFunction<void Function(ffi.Pointer<MpFaceMeshResult>)>();

  ffi.Pointer<ffi.Char> mp_face_mesh_last_error(
    ffi.Pointer<MpFaceMeshContext> context,
  ) {
    return _mp_face_mesh_last_error(context);
  }

  late final _mp_face_mesh_last_errorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<MpFaceMeshContext>)
        >
      >('mp_face_mesh_last_error');
  late final _mp_face_mesh_last_error = _mp_face_mesh_last_errorPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<MpFaceMeshContext>)
      >();

  ffi.Pointer<ffi.Char> mp_face_mesh_last_global_error() {
    return _mp_face_mesh_last_global_error();
  }

  late final _mp_face_mesh_last_global_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'mp_face_mesh_last_global_error',
      );
  late final _mp_face_mesh_last_global_error =
      _mp_face_mesh_last_global_errorPtr
          .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class MpFaceMeshContext extends ffi.Opaque {}

enum MpPixelFormat {
  MP_PIXEL_FORMAT_RGBA(0),
  MP_PIXEL_FORMAT_BGRA(1);

  final int value;
  const MpPixelFormat(this.value);

  static MpPixelFormat fromValue(int value) => switch (value) {
    0 => MP_PIXEL_FORMAT_RGBA,
    1 => MP_PIXEL_FORMAT_BGRA,
    _ => throw ArgumentError("Unknown value for MpPixelFormat: $value"),
  };
}

enum MpDelegateType {
  MP_DELEGATE_CPU(0),
  MP_DELEGATE_XNNPACK(1),
  MP_DELEGATE_GPU_V2(2);

  final int value;
  const MpDelegateType(this.value);

  static MpDelegateType fromValue(int value) => switch (value) {
    0 => MP_DELEGATE_CPU,
    1 => MP_DELEGATE_XNNPACK,
    2 => MP_DELEGATE_GPU_V2,
    _ => throw ArgumentError("Unknown value for MpDelegateType: $value"),
  };
}

final class MpImage extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int bytes_per_row;

  @ffi.UnsignedInt()
  external int format;
}

/// Android camera NV21 input (Y plane + interleaved VU plane).
final class MpNv21Image extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> y;

  external ffi.Pointer<ffi.Uint8> vu;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int y_bytes_per_row;

  @ffi.Int32()
  external int vu_bytes_per_row;
}

final class MpNormalizedRect extends ffi.Struct {
  @ffi.Float()
  external double x_center;

  @ffi.Float()
  external double y_center;

  @ffi.Float()
  external double width;

  @ffi.Float()
  external double height;

  @ffi.Float()
  external double rotation;
}

final class MpLandmark extends ffi.Struct {
  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double z;
}

final class MpFaceMeshResult extends ffi.Struct {
  external ffi.Pointer<MpLandmark> landmarks;

  @ffi.Int32()
  external int landmarks_count;

  external MpNormalizedRect rect;

  @ffi.Float()
  external double score;

  @ffi.Int32()
  external int image_width;

  @ffi.Int32()
  external int image_height;
}

final class MpFaceMeshCreateOptions extends ffi.Struct {
  external ffi.Pointer<ffi.Char> tflite_library_path;

  @ffi.Int32()
  external int threads;

  @ffi.Float()
  external double min_detection_confidence;

  @ffi.Float()
  external double min_tracking_confidence;

  @ffi.UnsignedInt()
  external int delegate;

  @ffi.Uint8()
  external int enable_smoothing;

  @ffi.Uint8()
  external int enable_roi_tracking;
}
